-- +goose Up
-- +goose StatementBegin

-- character_audit.seq: a monotonic, insertion-ordered tie-break for the newest-first reads (#399 item 5).
-- The reads ORDER BY at DESC, and before this the tie within a same-`at` burst broke on `id DESC` — a
-- RANDOM v4 UUID, so the order among same-instant rows was stable-but-arbitrary. A monotonic identity gives
-- the tie a MEANINGFUL, true insertion order (later-inserted first), matching the MemStore mirror's
-- reverse-insertion tie-break exactly so the hermetic and gated tests assert the same order.
--
-- This also makes the #399 batch-insert path (auditor.go, one multi-row pgx.Batch per drain) order-correct:
-- every row in one batch shares the batch transaction's now(), so `at` alone cannot order them — `seq`
-- increments per INSERT in the batch, so ORDER BY at DESC, seq DESC recovers within-batch insertion order.
--
-- GENERATED BY DEFAULT (not ALWAYS) AS IDENTITY: the writers never supply seq (it is engine bookkeeping,
-- not a caller field), so BY DEFAULT vs ALWAYS is immaterial for inserts; BY DEFAULT is chosen only so a
-- future data-migration/backfill could set it explicitly if ever needed.
--
-- DEPLOY NOTE — this ADD COLUMN uses a per-row computed default (nextval), so it is NOT a metadata-only
-- add: it REWRITES the whole table under an ACCESS EXCLUSIVE lock, assigning existing rows sequential
-- values (their relative order is unspecified but stable thereafter — acceptable for historical rows; new
-- rows are strictly insertion-ordered). On the very table the retention note flags as unbounded/high-volume
-- (`died` especially), that rewrite can be a lengthy, blocking op on a large production DB. It is cheap on a
-- small/fresh table (the current ~1-2k/box bar), but on a grown table schedule it in a maintenance window
-- (or split it: add a plain nullable BIGINT, backfill in batches, then attach the identity/NOT NULL).
ALTER TABLE character_audit ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE character_audit DROP COLUMN IF EXISTS seq;
-- +goose StatementEnd
