//go:build ignore

// gen.go — the generator for the overworld plains room grid (#361). Run it to regenerate 10-rooms.yaml:
//
//	go run gen.go
//
// The overworld is a 6-wide x 20-tall grid of walkable rooms the player crosses between Midgaard (south
// edge) and Darkwood (north edge). Hand-authoring 120 near-identical rooms is noise, so they are GENERATED
// from this compact spec and the output is committed. Every room is flagged `overworld` so the pack-global
// `room` display template (display_defs.yaml) can scope its minimap to the plains and return nil (built-in
// render) everywhere else. A few rooms carry a landmark flag (lake/house/hill) so the map draws an icon.
//
// Coordinates: coord [col,row,0], col 0..5, row 0..19 (north = +row, toward Darkwood; south = -row, toward
// Midgaard). Exits link orthogonal in-grid neighbours; the centre-column entry/exit rooms (c2_r0 / c2_r19)
// additionally bridge to Midgaard / Darkwood.
package main

import (
	"fmt"
	"os"
	"strings"
)

const (
	cols = 6
	rows = 20
	// The centre column (0..5) — the viewport is 5 wide, so the player enters/leaves on the middle column
	// and the connecting-city labels sit centred at the grid's south/north edges.
	gateCol = 2
)

// landmark maps a coord to a {flag, name, long} the generator stamps onto that room, for the map-icon demo.
type landmark struct{ flag, name, long string }

var landmarks = map[[2]int]landmark{
	{1, 6}:  {"landmark_lake", "The Shore of a Glassy Lake", "Still water stretches away, mirroring the wide sky. Reeds whisper at its edge."},
	{2, 6}:  {"landmark_lake", "A Glassy Lake", "Cool, clear water laps gently. Something silver flickers beneath the surface."},
	{4, 13}: {"landmark_house", "A Lonely Cottage", "A weathered stone cottage sits alone on the moor, a thin curl of smoke at its chimney."},
	{3, 9}:  {"landmark_hill", "A Windswept Hill", "The ground rises to a bare, grassy hill. From the top the plains roll away in every direction."},
}

// bandLong returns the flavour long for a plain (non-landmark) room, varied by how far north it is so the
// crossing reads as a journey from the city's fields to the dark forest's edge.
func bandLong(row int) string {
	switch {
	case row <= 3:
		return "Rolling grassland stretches out under an open sky. The walls of Midgaard stand at your back to the south."
	case row <= 9:
		return "Tall wild grasses ripple across an empty moor. Skylarks scatter as you pass."
	case row <= 15:
		return "The plains grow rugged and windswept, strewn with grey stones and gorse."
	default:
		return "A dark treeline looms to the north and the air turns cold. Darkwood is not far now."
	}
}

func ref(c, r int) string { return fmt.Sprintf("overworld:room:c%d_r%d", c, r) }

func main() {
	var b strings.Builder
	b.WriteString("# GENERATED by gen.go (#361) — do not edit by hand; run `go run gen.go` to regenerate.\n")
	b.WriteString("# The 6x20 overworld plains grid: 120 walkable rooms between Midgaard (south) and Darkwood (north).\n")
	b.WriteString("# Every room is flagged `overworld` so the pack-global `room` display template scopes its minimap\n")
	b.WriteString("# to the plains; landmark rooms carry an extra flag the map draws an icon for.\n")
	b.WriteString("zones:\n  - ref: overworld\n    rooms:\n")

	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			b.WriteString("      - ref: " + ref(c, r) + "\n")

			flags := []string{"overworld"}
			name := "The Open Plains"
			long := bandLong(r)
			if lm, ok := landmarks[[2]int{c, r}]; ok {
				flags = append(flags, lm.flag)
				name = lm.name
				long = lm.long
			}
			b.WriteString("        name: " + name + "\n")
			b.WriteString(fmt.Sprintf("        coord: [%d, %d, 0]\n", c, r))
			b.WriteString("        flags: [" + strings.Join(flags, ", ") + "]\n")
			b.WriteString("        long: >-\n          " + long + "\n")

			// Exits: orthogonal in-grid neighbours, then the city/forest bridges on the gate column.
			b.WriteString("        exits:\n")
			if r+1 < rows {
				b.WriteString("          north: " + ref(c, r+1) + "\n")
			}
			if r-1 >= 0 {
				b.WriteString("          south: " + ref(c, r-1) + "\n")
			}
			if c+1 < cols {
				b.WriteString("          east: " + ref(c+1, r) + "\n")
			}
			if c-1 >= 0 {
				b.WriteString("          west: " + ref(c-1, r) + "\n")
			}
			// South edge, centre column: the city gate. `south` (a spatial cross-zone exit) lets the map draw
			// the Midgaard label below; `enter` is the flavour verb a player uses to return to the city.
			if r == 0 && c == gateCol {
				b.WriteString("          south: midgaard:room:market\n")
				b.WriteString("          enter: midgaard:room:market\n")
			}
			// North edge, centre column: the forest edge. `north` gives the map the Darkwood label; `enter`
			// is the verb to step into the dark forest.
			if r == rows-1 && c == gateCol {
				b.WriteString("          north: darkwood:room:grove\n")
				b.WriteString("          enter: darkwood:room:grove\n")
			}
		}
	}

	out := "10-rooms.yaml"
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d rooms)\n", out, cols*rows)
}
